### ISSUE TITLE
cms_account_form not admin

### ISSUE THREAD

**Issue by OstapYakovenko** [OCA/website-cms#49] opened 2018-03-24 15:34 UTC
If user not admin, this module is not working

**Comment by pedrobaeza** [comment] 2018-03-24 15:43
Error? Traceback? Version? Steps to reproduce? Please give more information, or we shouldn't be able to fix anything.

**Comment by simahawk** [comment] 2018-04-24 15:24
@OstapYakovenko as said above: provide feedback. 
Also, note that if the issue is about permissions, it's your duty to take care of that (like grant read/write access to partner and user records).

**Comment by simahawk** [comment] 2018-05-24 10:35
closing since there's no feedback. Feel free to re-open it.

**Closed as completed by simahawk** 2018-05-24 10:35 UTC
